exports.exception = ((err, request, response, next) => {
    console.log('EXCEPTION: ' + err);
});